name: iOS Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
      branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/Xcode_14.0.1.app"
    - name: Build
      env: destination: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
      run: swift build -v
    - name: Run tests
      env: destination: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0'
      run: swift test -v
