name: iOS Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
      branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    name: Unit Testing on iOS 16.2

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version
    - name: Build and run tests
      run: xcodebuild test -scheme SwiftDithering -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' | xcpretty && exit ${PIPESTATUS[0]}
