name: iOS Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch

jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: iOS build setup
        run: >-
          xcodebuild test -workspace TestApp.xcodeproj/project.xcworkspace
          -scheme TestApp -destination 'platform=iOS Simulator,name=iPhone
          11,OS=13.7'
      - name: testing ... iPhone 11
        run: >-
          xcodebuild test -workspace TestApp.xcodeproj/project.xcworkspace
          -scheme TestApp -destination 'platform=iOS Simulator,name=iPhone
          11,OS=13.7'
